import localFont from "next/font/local";
import "./globals.css";
import { Open_Sans, Roboto } from 'next/font/google';


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: '--font-roboto', // Add CSS variable
});


export const metadata = {
  title: "Whale Lagoon - SMMA",
  description: "Generated by create next app",
  icons:{
    icon: ['/favicon/favicon.ico?v=4'],
    apple: ['/favicon/apple-touch-icon.png?v=4'],
    shortcut: ['/favicon/apple-touch-icon.png']
  }
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={` ${roboto.variable} antialiased `}
        // ${geistSans.variable} ${geistMono.variable} 
      >
        {children}
      </body>
    </html>
  );
}
